/**
  ******************************************************************************
  * @file    binmaster_protocol.c
  * @author  Protogen
  * @brief   Protocol Implementation File
  *
  *          Autogenerated file covering protocol implementation
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "binmaster_protocol.h"
/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/

/**
 * @brief Process protocol input
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
ProtocolErrorStatus processProtocolCommand(uint8_t *data, uint16_t length) {

  switch ((ProtocolCommands) data[0]) {
    case CYCLE:
      execute_cycle();
      break;
    case SET_ASCENT_RATE:
      execute_set_ascent_rate(&data[1], length - 1);
      break;
    case SET_DESCENT_RATE:
      execute_set_descent_rate(&data[1], length - 1);
      break;
    case SET_TIMEOUT:
      execute_set_timeout(&data[1], length - 1);
      break;
    case SET_RAMP_RATE:
      execute_set_ramp_rate(&data[1], length - 1);
      break;
    case GET_ASCENT_RATE:
      execute_get_ascent_rate();
      break;
    case GET_DESCENT_RATE:
      execute_get_descent_rate();
      break;
    case GET_TIMEOUT:
      execute_get_timeout(&data[1], length - 1);
      break;
    case GET_RAMP_RATE:
      execute_get_ramp_rate();
      break;
    case GET_PREVIOUS_LEVEL:
      execute_get_previous_level();
      break;
  }
  return PROTOCOL_SUCCESS;
}

/**
 * @brief Cycle Unit
 *
 * @retval None
 *
 */
__weak void execute_cycle(void) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Ascent rate (percent)
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
__weak void execute_set_ascent_rate(uint8_t *data, uint16_t length) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Descent rate (percent)
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
__weak void execute_set_descent_rate(uint8_t *data, uint16_t length) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief [quadrant] [Timeout (0.1ms)]
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
__weak void execute_set_timeout(uint8_t *data, uint16_t length) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Ramp rate
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
__weak void execute_set_ramp_rate(uint8_t *data, uint16_t length) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Get ascent rate (percent)
 *
 * @retval None
 *
 */
__weak void execute_get_ascent_rate(void) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Get descent rate (percent)
 *
 * @retval None
 *
 */
__weak void execute_get_descent_rate(void) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Timeout (10us)
 *
 * @param data    Data from stream
 * @param length  Length of data
 * @retval None
 *
 */
__weak void execute_get_timeout(uint8_t *data, uint16_t length) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Ramp rate
 *
 * @retval None
 *
 */
__weak void execute_get_ramp_rate(void) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}

/**
 * @brief Water level and Bottom level
 *
 * @retval None
 *
 */
__weak void execute_get_previous_level(void) {
  /* NOTE: This function should be implemented when the callback is needed
           within user file
  */
}